name: Pathfinding-in-stochastic-environments-APPO-training

global_settings:
  use_wandb: True
experiment_settings:
  save_every_sec: 120
  encoder_custom: pogema_residual
  train_for_env_steps: 1000000000
async_ppo:
  experiment_summaries_interval: 20
  ppo_epochs: 1
  batch_size: 1024
  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 12
  num_envs_per_worker: 8
  with_vtrace: True
  max_policy_lag: 100

environment:
  name: StochasticGrid-v0
  grid_config:
    map_name: '(wc3-[a-p]|sc1-[A-S]|sc1-WinterConquest|street-[A-P])'

    max_episode_steps: 256
    obs_radius: 5
    size: 64
    density: 0.3
    use_curriculum: True
    curriculum_score_horizon:
      grid_search: [256, 512, 1024]
    size_range: [ 5, 10 ]
    shake_r: 5
    show_range: [ 8, 16 ]
    hide_range: [ 8, 16 ]
    num_agents: 1
    so_density: 0.7
